
CREATE USER TEAM1 IDENTIFIED BY choi123;
--==>> User TEAM1이(가) 생성되었습니다.

GRANT CREATE SESSION TO TEAM1;
--==>> Grant을(를) 성공했습니다.
GRANT CREATE TABLE TO TEAM1;
--==>> Grant을(를) 성공했습니다.

GRANT CREATE VIEW TO TEAM1;
--==>> Grant을(를) 성공했습니다.

GRANT CREATE PROCEDURE TO TEAM1;
--==>> Grant을(를) 성공했습니다.

GRANT CONNECT,RESOURCE,UNLIMITED TABLESPACE TO TEAM1;
--==>> Grant을(를) 성공했습니다.

ALTER USER TEAM1 DEFAULT TABLESPACE USERS;
--==>> User TEAM1이(가) 변경되었습니다.

ALTER USER TEAM1 TEMPORARY TABLESPACE TEMP;
--==>> User TEAM1이(가) 변경되었습니다.

SELECT *
FROM DBA_SYS_PRIVS
WHERE GRANTEE = 'TEAM1';
--==>>
/*
TEAM1	CREATE TABLE	NO
TEAM1	CREATE PROCEDURE	NO
TEAM1	CREATE SESSION	NO
TEAM1	UNLIMITED TABLESPACE	NO
TEAM1	CREATE VIEW	NO
*/