--○ 테이블 코멘트 조회
SELECT *
FROM USER_TAB_COMMENTS
ORDER BY COMMENTS;


--테이블 Comment 설정
--COMMENT ON TABLE [테이블명] IS [Comment];

--○ ADMIN 관리자계정에 코멘트 달기
COMMENT ON TABLE ADMIN IS '0. 관리자 계정';

--○ TBL_PROF 교수자계정에 코멘트 달기
COMMENT ON TABLE TBL_PROF IS '1-1. 교수자 계정';

--○ TBL_STU 학생계정에 코멘트 달기
COMMENT ON TABLE TBL_STU IS '1-2. 학생 계정';

--○ TBL_COU 과정계정에 코멘트 달기
COMMENT ON TABLE TBL_COU IS '1-3. 과정 계정';

--○ TBL_SUB 과목계정에 코멘트 달기
COMMENT ON TABLE TBL_SUB IS '1-4. 과목 계정';

--○ TBL_GRADE 성적계정에 코멘트 달기
COMMENT ON TABLE TBL_GRADE IS '1-5. 성적 계정';

--○ TBL_TEXTBOOK 교재계정에 코멘트 달기
COMMENT ON TABLE TBL_TEXTBOOK IS '1-6. 교재 계정';

--○ TBL_CLASSROOM 강의실계정에 코멘트 달기
COMMENT ON TABLE TBL_CLASSROOM IS '1-7. 강의실 계정';

--○ TBL_OPEN_COU 개설과정계정에 코멘트 달기
COMMENT ON TABLE TBL_OPEN_COU IS '2-1. 개설과정계정';

--○ TBL_APPLY_COU 수강신청계정에 코멘트 달기
COMMENT ON TABLE TBL_APPLY_COU IS '3-1. 수강신청계정';

--○ TBL_DROP_COU 강의폐강계정에 코멘트 달기
COMMENT ON TABLE TBL_DROP_COU IS '3-2. 강의폐강계정';

--○ TBL_OPEN_SUB 개설과목계정에 코멘트 달기
COMMENT ON TABLE TBL_OPEN_SUB IS '4-1. 개설과목계정';

--○ TBL_DROP_STU 중도탈락계정에 코멘트 달기
COMMENT ON TABLE TBL_DROP_STU IS '4-2. 중도탈락계정';

--○ VIEW_CONSTCHECK 제약조건확인계정 코멘트 달기
COMMENT ON TABLE VIEW_CONSTCHECK IS '제약조건확인계정';

--○ 테이블 안 성적컬럼 코멘트 조회
SELECT *
FROM ALL_COL_COMMENTS
WHERE TABLE_NAME = 'TBL_GRADE';


--컬럼 Comment 설정
--COMMENT ON COLUMN [테이블명].[컬럼명] IS '[Comment]';

--○ TBL_GRADE 성적계정 안 컬럼의 코멘트 달기
COMMENT ON COLUMN TBL_GRADE.GRADE_CODE IS '성적';
COMMENT ON COLUMN TBL_GRADE.APPLY_COU_CODE IS '수강';
COMMENT ON COLUMN TBL_GRADE.OPEN_SUB_CODE IS '개설과목';
COMMENT ON COLUMN TBL_GRADE.ATTENDANCE IS '출결점수';
COMMENT ON COLUMN TBL_GRADE.PRACTICAL IS '실기점수';
COMMENT ON COLUMN TBL_GRADE.WRITE IS '필기점수';


--○ 테이블 안 교재컬럼 코멘트 조회
SELECT *
FROM ALL_COL_COMMENTS
WHERE TABLE_NAME = 'TBL_OPEN_SUB';

--○ TBL_OPEN_SUB 개설과목 컬럼 코멘트 조회
COMMENT ON COLUMN TBL_OPEN_SUB.OPEN_SUB_CODE IS '개설과목';
COMMENT ON COLUMN TBL_OPEN_SUB.OPEN_COU_CODE IS '개설과정';
COMMENT ON COLUMN TBL_OPEN_SUB.SUB_CODE IS '과목';
COMMENT ON COLUMN TBL_OPEN_SUB.PROF_ID IS '교수번호';
COMMENT ON COLUMN TBL_OPEN_SUB.BOOK_NO IS '교재번호';
COMMENT ON COLUMN TBL_OPEN_SUB.ROOM_NO IS '강의실코드';
COMMENT ON COLUMN TBL_OPEN_SUB.SUB_START IS '과목시작일';
COMMENT ON COLUMN TBL_OPEN_SUB.SUB_END IS '과목종료일';
COMMENT ON COLUMN TBL_OPEN_SUB.ATTE_RATIO IS '출결배점';
COMMENT ON COLUMN TBL_OPEN_SUB.PRACT_RATIO IS '실기배점';
COMMENT ON COLUMN TBL_OPEN_SUB.WRITE_RATIO IS '필기배점';
